# 9주차 예외 처리

## 예외 처리란?

프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것이다.

예외 처리를 통해 특정 에러가 날 때 걸맞는 적절한 처리를 할 수 있도록 프로그램을 구성할 수 있다.

## 자바에서 예외 처리 방법(try, catch, throw, throws, finally)

아래는 RuntimeException을 강제로 발생 시키는 방법이다.

```java
public class ExceptionMain {
	
	public static void main(String[] args) {
		callRunTimeException();
		
		System.out.println("after Runtim Exception");
	}

	public static void callRunTimeException() {
		throw new RuntimeException("runtime exception call");
	}
}

/*
결과 : 
Exception in thread "main" java.lang.RuntimeException: test
	at ExceptionMain.callRunTimeException(ExceptionMain.java:13)
	at ExceptionMain.main(ExceptionMain.java:9)
*/
```

위 코드는 중간에 RuntimeException 이라는 예외를 발생 시키므로 “after Runtime Exception”을 출력하지 않는다.

그렇다면 위 Exception이 발생하더라도 다음 로직을 실행시키려면 어떻게 해야할까?

### try - catch

try-catch 문은 java에서 예외처리를 할때 사용할수 있는 문법이다.

```java
try {
	// 예외가 발생할 수 있는 구문
} catch(RuntimeException e) {
	// 예외 발생시 예외 처리 구문
} finally {
	// 예외 발생 유무와 관계없이 실행 (최종 처리를 위함)
}
```

즉 위에서 예외를 발생한 구문을 try-catch 블록을 이용해서, 다음과 같이 코드를 변경해보자

```java
public class ExceptionMain {

    public static void main(String[] args) {
        try {
            callRunTimeException();
        } catch (RuntimeException e) {
            System.out.println(e); // 1. java.lang.RuntimeException: runtime exception call
        } finally {
            System.out.println("try-catch out"); // 2. try-catch out
        }

        System.out.println("after Runtime Exception!"); // 3. after Runtime Exception!
    }

    public static void callRunTimeException() {
        throw new RuntimeException("runtime exception call");
    }
}

/*
java.lang.RuntimeException: runtime exception call
try-catch out
after Runtime Exception!
*/
```

즉 아래와 같이 try-catch 구문으로 예외 처리를 진행할 수 있다.

### **throw**

throw는 아래와 같이 Exception을 강제로 발생시킬때 사용한다.

```java
public static void callRunTimeException() {
        throw new RuntimeException("runtime exception call"); // 예외 발생
    }
```

### **throws**

throws는 예외가 발생했을때, 해당 method를 호출한 상위 메소드로 Exception을 던져준다.

```java
public static void callRunTimeException() throws RuntimeException {
        throw new RuntimeException("runtime exception call");
    }
```

그런데 아래와 위와 같이, throws를 추가하여도 해당 메소드를 호출한 main 메소드에서는 별다른 예외처리를 안해주어도 된다. 왜 그럴까? (아래 Checked Exception, Unchecked Exception을 확인하면 이해가 될 것이다.)

## 자바가 제공하는 예외 계층 구조

![image](https://user-images.githubusercontent.com/10612909/192112948-41159077-e358-46f0-ad3b-5a92a7a99522.png)

위 그림은 자바가 제공하는 계층 구조를 그림으로 표현한 것이다. Throwble 클래스 역시 Object 클래스를 상속한다. 그리고 Error 클래스와 Exception 클래스로 나뉘어 진다.

## Exception과 Error의 차이는?

### 에러 Error

에러는 메모리 부족(OutOfMemoryError)이나 스택오버플로우(StackOverflowError)와 같은 발생하게 되면 복구할 수 없는 심각한 수준의 오류를 뜻한다. 시스템에 비정상적인 상황이 생겼을 때 발생하므로 System level의 문제이다.

### 예외 Exception

예외는 개발자가 작성한 로직 내에서 발생한 오류를 뜻한다. 따라서 발생하더라도 개발자가 이에 대한 적절한 코드를 미리 작성해 놓음으로써 프로그램의 비정상적인 종료와 같은 오류를 방지할 수 있다.

- **에러(error)** 프로그램 코드에 의해서 수습될 수 **없는** 심각한 오류
- **예외(exception)** 프로그램 코드에 의해서 수습될 수 **있는** 상대적으로 미약한 오류

**Exception과 Error는 System Level의 문제와 Application Level의 문제의 차이이다.**

## RuntimeException과 RE가 아닌 것의 차이는?

상속 계층도에서 볼 수 있듯이 예외 클래스는 두 그룹으로 나눌 수 있다.

- Excepiton클래스와 그 자손들
- RuntimeException클래스와 그 자손들

### Unchecked Exception

Unchecked Exception(RuntimeException클래스와 그 자손들)은 주로 프로그래머의 실수에 의해서 발생될 수 있는 예외들로 자바의 프로그래밍 요소들과 관계가 깊다.

예를 들어

- 배열의 범위를 벗어난다던가(ArrayIndexOutOfBoundsException)
- 값이 null인 참조변수의 멤버를 호출하려 했다던가(NullPointerException)
- 클래스 간의 형변환을 잘못했다던가(ClassCastException)
- 정수를 0으로 나누려고(ArithmeticException)

하는 경우에 발생한다.

명시적인 처리를 강제하지 않고, 실행되는 시점(Runtime)에 확인한다.

### Checked Exception

Checked Exception(RE클래스들을 제외한 나머지 클래스들)은 주로 외부의 영향으로 발생하는 것들로, 프로그램 사용자들의 동작에 의해서 발생하는 경우가 많다.

예를 들어

- 존재하지 않는 파일의 이름을 입력했다던가(FileNotFoundException)
- 실수로 클래스의 이름을 잘못 적었다던가(ClassNotFoundException)
- 입력한 데이터 형식이 잘못된(DataFormatException)

경우에 발생한다.

이름에서 알 수 있듯이 반드시 예외를 처리해야하고, 컴파일되는 시점에 확인한다.

# 커스텀한 예외 만드는 방법

```java
public static class MyException extends Exception{
        private final Integer code;

        public MyException(String message, Integer code) {
            super(message);
            this.code = code;
        }

        @Override
        public synchronized Throwable getCause() {
            System.err.println("code = " + code);
            return super.getCause();
        }
    }

    public static void exception3() throws MyException {
        // 특정 조건 발생시 -> ex) 5 / 0
        throw new MyException("some-message", 500);
    }
}
```

- Spring

```java
@RestControllerAdvice
public static class ExceptionHandlers {
    @ExceptionHandler(RuntimeException.class)
    ResponseEntity<ErrorResponse> handleConstraintViolationException(RuntimeException e) {
        final ErrorResponse response = ErrorResponse.of(ErrorCode.MEMID_NOT_FOUNDED);
        return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
    }
}
```

Exception이 발생했을 경우 이를 캐치해줄 ExceptionHandler를 만들어준다.

여기서는 RuntimeException이 발생한 경우 내가 커스텀한 Response로 예외를 뿌려주게 된다.

```java
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class ErrorResponse {

    private String message;
    private int status;
    private String code;

    private ErrorResponse(final ErrorCode code) {
        this.message = code.getMessage();
        this.status = code.getStatus();
        this.code = code.getCode();
    }

    public static ErrorResponse of(final ErrorCode code) {
        return new ErrorResponse(code);
    }

}
```

리턴할 ResponseEntity에 담아줄 ErrorResponse 객체를 만들어준다.

```java
public enum ErrorCode {
    MEMID_NOT_FOUNDED(400, "member.memId", "memId는 반드시 입력되어야 합니다."),
		MEMCODE_NOT_FOUNDED(401, "member.memCode", "memCode는 반드시 입력되어야 합니다.");

    private final String code;
    private final String message;
    private final int status;

    ErrorCode(final int status, final String code, final String message) {
        this.status = status;
        this.message = message;
        this.code = code;
    }

    public String getMessage() {
        return this.message;
    }

    public String getCode() {
        return code;
    }

    public int getStatus() {
        return status;
    }
}
```

enum을 만들어 각 CASE에 대한 값을 지정해 넣어준다. 

```java
public static class NoResultMemCodeException extends RuntimeException{
        public NoResultMemCodeException(String message) {
            super(message);
        }

        public NoResultMemCodeException() {
            super();
        }
    }
```

마지막으로 커스텀 Exception을 만들어 준다.
